### ISSUE TITLE
Fixed XSS in hooks/SummaryReport.php

### ISSUE THREAD

**Issue by ghost** [bigprof-software/online-invoicing-system#10]
There is an XSS vulnerability in the said file.

I have created a pull request which fixes it.
The vulnerability details and fix are in the following pull request.

 https://github.com/418sec/online-invoicing-system/pull/6

**Comment by bigprof** [comment]
Thank you so much for investigating and providing a suggested fix for this issue. I've implemented an alternative fix that involves less code and applies in a centralized manner.
#f839f7a8e
