### ISSUE TITLE
In the Invoice items table the invoice field is read only by default

### ISSUE THREAD

**Issue by NjengaFelix** [bigprof-software/online-invoicing-system#7]
![Screenshot (4)](https://user-images.githubusercontent.com/32095327/104607030-6df5bd00-5691-11eb-9c29-c27eff2b8eb9.png)

Should it be a read only field?

**Comment by bigprof** [comment]
Well, the reason it's read-only is the way it gets populated in the app. You should start by creating an invoice, then after saving it, you can start adding items by clicking the 'Add new' button below the invoice form. This would automatically set the invoice field in the invoice_items record to the current invoice. Being read-only prevents changing the invoice by mistake.

But of course, you can change it if you don't want that behavior :)

**Comment by NjengaFelix** [comment]
I agree 100% i didn't first start by creating an invoice. It should be read-only. I have identified my mistake
